name: Policy detector (iamlive)

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: The target infraestruture 
        required: true
        default: ''
        type: choice  
        options:
          - main bootstrap
          - main infra
          - env dev
          - env prod
          - env staging
jobs:
  DetectPolicies:
    runs-on: ubuntu-latest

    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: eu-central-1

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Install iamlive
        run: |
          set -e
          # Resolve a URL do asset linux-amd64 da última release automaticamente
          ASSET_URL=$(curl -s https://api.github.com/repos/iann0036/iamlive/releases/latest \
            | grep "browser_download_url" \
            | grep "linux-amd64.tar.gz" \
            | cut -d '"' -f 4)

          if [ -z "$ASSET_URL" ]; then
            echo "Não encontrei o asset linux-amd64 na última release"
            exit 1
          fi

          echo "Baixando: $ASSET_URL"
          curl -L "$ASSET_URL" -o iamlive.tar.gz

          # Extrai o binário
          tar xvzf iamlive.tar.gz

          # Move para um diretório já presente no PATH
          sudo mv iamlive /usr/local/bin/

          # Garante permissão de execução
          sudo chmod +x /usr/local/bin/iamlive

          # Confirma que está no PATH e funcionando
          which iamlive
          iamlive --version || iamlive -h

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/iamlive-role
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Select evironment
        id: setdir
        run: |
          case "${{github.event.inputs.environment}}" in
            "main bootstrap")
              echo "dir=./terraform/bootstrap/main_bootstrap" >> "$GITHUB_OUTPUT"
              ;;
            "main infra")
              echo "dir=./terraform/main_infra" >> "$GITHUB_OUTPUT"
              ;;
            "dev")
              echo "dir=./terraform/main_infra/env/dev" >> "$GITHUB_OUTPUT"
              ;;
            "staging")
              echo "dir=./terraform/main_infra/env/staging" >> "$GITHUB_OUTPUT"
              ;;
            "prod")
              echo "dir=./terraform/main_infra/env/prod" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Invalid environment: ${{ github.event.inputs.environment }}"
              exit 1
              ;;
          esac

      - name: Terraform Init
        working-directory: ${{ steps.setdir.outputs.dir }}
        run: terraform init

      - name: Run iamlive and Terraform
        working-directory: ${{ steps.setdir.outputs.dir }}
        run: |
          # Inits iamlive in background and set a output file
          iamlive -mode csm -csm-port 31000 -output-file policy_output.json &
          echo "IAMLIVE_PID=$!" >> $GITHUB_ENV
          sleep 2
          
          # Actives CSM and run terraform plan
          export AWS_CSM_ENABLED=true
          export AWS_CSM_PORT=31000
          export AWS_CSM_HOST=127.0.0.1
          
          terraform plan
          
          # Shuts down iamlive and forces json save
          kill -SIGINT $IAMLIVE_PID

      - name: Upload Policy Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iam-policy
          path: policy_output.json
