name: Terraform Infrastructure CI/CD

on:
  workflow_dispatch:
    inputs:
      run_plan:
        description: 'Run plan'
        required: true
        default: false
        type: boolean
      run_apply:
        description: 'Run apply'
        required: true
        default: false
        type: boolean
      run_plan_destroy:
        description: 'Run plan destroy'
        required: true
        default: false
        type: boolean
      run_destroy:
        description: 'Run destroy'
        required: true
        default: false
        type: boolean
      environment:
        description: "Target infraestruture environment"
        required: true 
        default: ''
        type: choice  
        options:
          - env global
          - env dev
          - env staging
          - env prod

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-infra
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest

    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 1.0.0

      - name: Select Environment
        id: set_env
        run: |
          case "${{ github.event.inputs.environment }}" in
            "env global")
              echo "dir=./terraform/infrastructure/global" >> "$GITHUB_OUTPUT"
              echo "role_name=infrastructure-cicd-role" >> "$GITHUB_OUTPUT"
              echo "bucket_name=global-infrastructure-bucket-${{secrets.ACCOUNT_ID}}" >> "$GITHUB_OUTPUT"
              echo "use_terragrunt=false" >> "$GITHUB_OUTPUT"
              ;;
            "env dev")
              echo "dir=./terraform/infrastructure/envs/dev" >> "$GITHUB_OUTPUT"
              echo "role_name=dev-cicd-environment-role" >> "$GITHUB_OUTPUT"
              echo "bucket_name=dev-environment-bucket-${{secrets.ACCOUNT_ID}}" >> "$GITHUB_OUTPUT"
              echo "use_terragrunt=true" >> "$GITHUB_OUTPUT"
              ;;
            "env staging")
              echo "dir=./terraform/infrastructure/envs/staging" >> "$GITHUB_OUTPUT"
              echo "role_name=staging-cicd-environment-role" >> "$GITHUB_OUTPUT"
              echo "bucket_name=staging-environment-bucket-${{secrets.ACCOUNT_ID}}" >> "$GITHUB_OUTPUT"
              echo "use_terragrunt=true" >> "$GITHUB_OUTPUT"
              ;;
            "env prod")
              echo "dir=./terraform/infrastructure/envs/prod" >> "$GITHUB_OUTPUT"
              echo "role_name=prod-cicd-environment-role" >> "$GITHUB_OUTPUT"
              echo "bucket_name=prod-environment-bucket-${{secrets.ACCOUNT_ID}}" >> "$GITHUB_OUTPUT"
              echo "use_terragrunt=true" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Invalid environment: ${{ github.event.inputs.environment }}"
              exit 1
              ;;
          esac

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{steps.set_env.outputs.role_name}}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      # Standard Terraform Workflow
      - name: Terraform Init
        if: steps.set_env.outputs.use_terragrunt == 'false'
        working-directory: ${{ steps.set_env.outputs.dir }}
        run: |
            terraform init \
              -backend-config="bucket=${{steps.set_env.outputs.bucket_name}}"

      - name: Terraform Validate
        if: steps.set_env.outputs.use_terragrunt == 'false'
        working-directory: ${{ steps.set_env.outputs.dir }}
        run: terraform validate

      - name: DebugChecker
        working-directory: ${{ steps.set_env.outputs.dir }}
        run: |
          echo ${{ steps.set_env.outputs.dir }}; 
          ls

      # Inputs are compared directly as booleans, outputs are compared as strings
      - name: Terraform Plan
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: (github.event.inputs.run_apply == true || github.event.inputs.run_plan == true) && steps.set_env.outputs.use_terragrunt == 'false'
        run: terraform plan 

      - name: Terraform Apply
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: github.event.inputs.run_apply == true && steps.set_env.outputs.use_terragrunt == 'false'
        run: terraform apply -auto-approve 

      - name: Terraform Plan destroy
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: (github.event.inputs.run_destroy == true || github.event.inputs.run_plan_destroy == true) && steps.set_env.outputs.use_terragrunt == 'false'
        run: terraform plan --destroy 

      - name: Terraform Destroy
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: github.event.inputs.run_destroy == true && steps.set_env.outputs.use_terragrunt == 'false'
        run: terraform destroy -auto-approve 

      # Terragrunt Workflow
      - name: Terragrunt Plan
        if: (github.event.inputs.run_apply == true || github.event.inputs.run_plan == true) && steps.set_env.outputs.use_terragrunt == 'true'
        working-directory: ${{ steps.set_env.outputs.dir }}
        run: |
          terragrunt run --all plan --non-interactive

      - name: Terragrunt Apply
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: github.event.inputs.run_apply == true && steps.set_env.outputs.use_terragrunt == 'true'
        run: |
          terragrunt run --all apply --non-interactive

      - name: Terragrunt Plan destroy
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: (github.event.inputs.run_destroy == true || github.event.inputs.run_plan_destroy == true) && steps.set_env.outputs.use_terragrunt == 'true'
        run: |
          terragrunt run --all plan -destroy --non-interactive

      - name: Terragrunt Destroy
        working-directory: ${{ steps.set_env.outputs.dir }}
        if: github.event.inputs.run_destroy == true && steps.set_env.outputs.use_terragrunt == 'true'
        run: |
          terragrunt run --all destroy --non-interactive