name: Terraform Infrastructure CI/CD

on:
  workflow_dispatch:
    inputs:
      run_plan:
        description: 'Run plan'
        required: true
        default: false
        type: boolean
      run_apply:
        description: 'Run apply'
        required: true
        default: false
        type: boolean
      run_plan_destroy:
        description: 'Run plan destroy'
        required: true
        default: false
        type: boolean
      run_destroy:
        description: 'Run destroy'
        required: true
        default: false
        type: boolean
      environment:
        description: "Target infraestruture environment"
        required: true 
        default: ''
        type: choice  
        options:
          - main bootstrap
          - main infra
          - env dev
          - env staging
          - env prod

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-infra
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform Bootstrap Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/bootstrap/main_bootstrap

    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/terraform-bootstrap-role
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
    
      - name: Select Environment
        run: |
          case "${{ github.event.inputs.environment }}" in
            "main bootstrap")
              echo "dir=./terraform/bootstrap/main_bootstrap" >> "$GITHUB_OUTPUT"
              ;;
            "main infra")
              echo "dir=./terraform/main_infra" >> "$GITHUB_OUTPUT"
              ;;
            "env dev")
              echo "dir=./terraform/main_infra/env/dev" >> "$GITHUB_OUTPUT"
              ;;
            "env staging")
              echo "dir=./terraform/main_infra/env/staging" >> "$GITHUB_OUTPUT"
              ;;
            "env prod")
              echo "dir=./terraform/main_infra/env/prod" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Invalid environment: ${{ github.event.inputs.environment }}"
              exit 1
              ;;
          esac

      - name: Terraform Init
        working-directory: ${{ steps.setdir.outputs.dir }}
        run: |
            terraform init \
            -backend-config="bucket=terraform-main-bootstrap-bucket-${{ env.AWS_REGION }}" \
            -backend-config="key=enviroment/bootstrap/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        working-directory: ${{ steps.setdir.outputs.dir }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ steps.setdir.outputs.dir }}
        if: ${{github.event.inputs.run_apply == 'true' || github.event.inputs.run_plan == 'true'}}
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ${{ steps.setdir.outputs.dir }}
        if: ${{ github.event.inputs.run_apply == 'true' }}
        run: terraform apply -auto-approve -input=false

      - name: Terraform Plan destroy
        working-directory: ${{ steps.setdir.outputs.dir }}
        if: ${{github.event.inputs.run_destroy == 'true' || github.event.inputs.run_plan_destroy == 'true'}}
        run: terraform plan --destroy -input=false

      - name: Terraform Destroy
        working-directory: ${{ steps.setdir.outputs.dir }}
        if: ${{ github.event.inputs.run_destroy == 'true' }}
        run: terraform destroy -auto-approve -input=false