name: Policy detector 

on: 
  workflow_dispatch:
    inputs:
      infra:
        description: The target infraestruture 
        required: true
        default: ''
        type: choice  
        options:
          - main bootstrap
          - main infra
          - env dev
          - env prod
          - env stating
jobs:
  DetectPolicies:
    runs-on: ubuntu-latest

      
